### ISSUE TITLE
Refactor project

### ISSUE THREAD

**Issue by sofianedjerbi** [Hynse/FoliaFlow#11]
It would be nice to split that huge main file into smaller and functional files for easier maintaining / optimization.
I consider creating a PR.

**Comment by MidnightTale** [comment]
I agree. thank you for comment. go for it if you want! :D

**Comment by sofianedjerbi** [comment]
Is there a discord for this project or for your organization ?

**Comment by MidnightTale** [comment]
Don't have because hynse is smp we discord not main English. you can add me in discord `MidnightTale_#2179`.

**Comment by sofianedjerbi** [comment]
Your friend requests are closed: `sofiane#4308` if you want to add me
