### ISSUE TITLE
Block entities don‘t move in the end

### ISSUE THREAD

**Issue by 1264175987** [Hynse/FoliaFlow#23]
Block entities don‘t move in the end
server jar : folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf
plugin version 2.3_a

**Comment by Sauvignon520** [comment]
I also encountered the same problem and don't know how to fix it

**Comment by CengJingMiLu** [comment]
I also encountered the same problem,it lose its velocity

**Comment by MidnightTale** [comment]
sorry for being late i will look into issue soon. have news will tell.

**Comment by MidnightTale** [comment]
can anyone try with `unsafe end teleport` option on in `config/paper-global.yml`?
```yml
unsupported-settings:
  allow-unsafe-end-portal-teleportation: true
```

**Comment by MidnightTale** [comment]
can you try [version 2.4](https://github.com/MidnightTale/FoliaFlow/actions/runs/9260475605) ?

don't forgot to delete old config in `plugins/FoliaFlow/config.yml`

**Comment by 1264175987** [comment]
I tried 2.4 version, It still doesn't look working.The entity has no momentum。

**Comment by MidnightTale** [comment]
> I tried 2.4 version, It still doesn't look working.The entity has no momentum。

i can reproduce on last commit and fixed

can i get folia commit version do `/version`

**Comment by 1264175987** [comment]
This server is running Folia version git-Folia-"8210085" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 8210085)

**Comment by MidnightTale** [comment]
Are you using folia fork ?

i can't find commit "8210085" in official repo

**Comment by 1264175987** [comment]
This is an automatic build of the official version.
https://github.com/Echoflare/Folia
Is there something wrong with this version?

**Comment by MidnightTale** [comment]
i just need to find what version and commit so i can try to reproduce what is cause the issue

**Comment by MidnightTale** [comment]
i can't reproduce on https://github.com/Echoflare/Folia commit 8210085

what design of sand dupe you using ? or maybe something wrong with you configuration ?

https://github.com/MidnightTale/FoliaFlow/assets/125941391/2737ae77-faf5-49d9-af19-c92988258f8e

**Comment by 1264175987** [comment]
I will replace a new game save file for testing.Maybe there is something wrong with my server.
