### ISSUE TITLE
A Folia Async Task Err

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [Hynse/FoliaFlow#8]
this is the lastlog, I try to change plugins to fix it but it seems didin't work...
[latest.log](https://github.com/Hynse/FoliaFlow/files/11303901/latest.log)

**Comment by MidnightTale** [comment]
can you send folia version use `/ver` and what foliaflow version using?

**Comment by xiaoyueyoqwq** [comment]
> can you send folia version use `/ver` and what foliaflow version using?

Oh, maybe I should try to update my Folia...
System said I was 10 versions behide :(
I will try your plugin in the last build, thank you!

**Comment by MidnightTale** [comment]
alright if still have issues report it
